channels:
- conda-forge
dependencies:
- python
- flux-core
- pysqa =0.1.20
- cloudpickle =3.0.0
- executorlib-core =0.0.1
- numpy =1.26.4
- h5py =3.11.0
- h5io =0.2.2
- pip:
    - git+https://github.com/executorlib/executorlib-core.git
